### ISSUE TITLE
java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by mfrancese-sogei** [EMCECS/atmos-client-java#10]
Hi,
we are in contact with your commercial support who advised us to open an urgent issue here.
My company is using the atmos-client-java library to connect to an ECS remote repository.

Randomly, we have this error:
```
com.sun.jersey.api.client.ClientHandlerException: java.net.SocketException: Connection reset
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
        at com.emc.atmos.api.jersey.ChecksumFilter.handle(ChecksumFilter.java:49)
        at com.emc.atmos.api.jersey.ErrorFilter.handle(ErrorFilter.java:48)
        at com.emc.atmos.api.jersey.RetryFilter.handle(RetryFilter.java:64)
        at com.emc.atmos.api.jersey.AuthFilter.handle(AuthFilter.java:53)
        at com.sun.jersey.api.client.Client.handle(Client.java:652)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)
        at com.emc.atmos.api.jersey.AtmosApiClient.createObject(AtmosApiClient.java:205)
```
Naturally the problem is solved temporarily by restarting the application server.

The problem appears to be caused by the ecs server or one of the network devices involved, which are resetting the connection.

Can we set a property to configure the connection pool in order to validate the connections before using them?
We cannot act on the connections of our application server because the invocations are made at a low level from the library through the Jersey client.

Thanks in advance.

**Comment by xiaoxin-ren** [comment]
Thanks for raising the issue, are you asking for PoolingClientConnectionManager to be configurable from a property? I would suggest to work with Customer Support like issue#11, 200 max-connections is not extreme for a cluster.
